export const DISMISS_USER = 'DISMISS_USER'
export const LIST_USERS = 'LIST_USERS'
export const GET_USER = 'GET_USER'
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'
